exp_name: exp_0001
data_dir: /home/sjqian/300W/Image
img_list: /home/sjqian/300W/train.txt

batch_size: 4
init_batches: 4
spatial_size: 256
bottleneck_factor: 2

lr: 1.0e-3
lr_decay_begin: 1000
lr_decay_end: 50000
log_freq: 250
ckpt_freq: 5000
test_freq: 100
drop_prob: 0.1
sigma: 1
